// Generated by CoffeeScript 1.9.2
(function() {
  var Game,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Game = (function() {
    var LOOP_TIME_INTERVAL, SPEED_LIMIT;

    function Game() {
      this.loop = bind(this.loop, this);
      this.doPhysics = bind(this.doPhysics, this);
      this.movePlayer = bind(this.movePlayer, this);
      this.broadcastState = bind(this.broadcastState, this);
      this.deletePlayer = bind(this.deletePlayer, this);
      this.handleMove = bind(this.handleMove, this);
      this.worldWidth = 4000;
      this.worldHeight = 4000;
      this.players = {};
      this.nextPlayerId = 0;
      this.enemies = {};
      this.bullets = {};
      this.io = null;
    }

    Game.prototype.start = function(io) {
      console.log("Game server started!");
      this.io = io;
      io.on('connection', (function(_this) {
        return function(socket) {
          return _this.initializeConnection(socket);
        };
      })(this));
      return this.loop();
    };

    Game.prototype.initializeConnection = function(socket) {
      var newPlayerId;
      newPlayerId = this.nextPlayerId++;
      this.createPlayer(newPlayerId);
      socket.on("move", this.handleMove);
      socket.on("disconnect", (function(_this) {
        return function() {
          console.log("Player disconnected!", newPlayerId);
          return _this.deletePlayer(newPlayerId);
        };
      })(this));
      return socket.emit('initialize', {
        playerId: newPlayerId
      });
    };

    Game.prototype.handleMove = function(message) {
      var mouseX, mouseY, player, playerId;
      if ((message == null) || (message.playerId == null)) {
        return;
      }
      mouseX = message.mouseX, mouseY = message.mouseY, playerId = message.playerId;
      if ((mouseX == null) || (mouseY == null)) {
        return;
      }
      player = this.players[playerId];
      player.mouseX = mouseX;
      return player.mouseY = mouseY;
    };

    Game.prototype.createPlayer = function(playerId) {
      var x, y;
      x = Math.random() * this.worldWidth;
      y = Math.random() * this.worldHeight;
      return this.players[playerId] = {
        type: 'player',
        id: playerId,
        r: 20,
        x: x,
        y: y,
        vx: 0,
        vy: 0,
        mouseX: x,
        mouseY: y
      };
    };

    Game.prototype.deletePlayer = function(playerId) {
      if (playerId in this.players) {
        return delete this.players[playerId];
      }
    };

    Game.prototype.broadcastState = function() {
      var bullet, enemy, entities, id, player, ref, ref1, ref2, state;
      entities = [];
      ref = this.enemies;
      for (id in ref) {
        enemy = ref[id];
        entities.push(enemy);
      }
      ref1 = this.players;
      for (id in ref1) {
        player = ref1[id];
        entities.push(player);
      }
      ref2 = this.bullets;
      for (id in ref2) {
        bullet = ref2[id];
        entities.push(bullet);
      }
      state = {
        worldWidth: this.worldWidth,
        worldHeight: this.worldHeight,
        entities: entities
      };
      return this.io.sockets.emit('state', state);
    };

    SPEED_LIMIT = 300;

    Game.prototype.movePlayer = function(player, dt) {
      var ax, ay, clampedX, clampedY, speed;
      ax = player.mouseX - player.x;
      ay = player.mouseY - player.y;
      player.vx += dt * ax;
      player.vy += dt * ay;
      player.x += dt * player.vx;
      player.y += dt * player.vy;
      clampedX = false;
      clampedY = false;
      if (player.x - player.r < 0) {
        clampedX = true;
        player.x = player.r;
      }
      if (player.x + player.r > this.worldWidth) {
        clampedX = true;
        player.x = this.worldWidth - player.r;
      }
      if (player.y - player.r < 0) {
        clampedY = true;
        player.y = player.r;
      }
      if (player.y + player.r > this.worldHeight) {
        clampedY = true;
        player.y = this.worldHeight - player.r;
      }
      if (clampedX) {
        player.vx = 0;
      }
      if (clampedY) {
        player.vy = 0;
      }
      speed = Math.sqrt(player.vx * player.vx + player.vy * player.vy);
      if (speed > SPEED_LIMIT) {
        player.vx *= SPEED_LIMIT / speed;
        player.vy *= SPEED_LIMIT / speed;
      }
      return player;
    };

    Game.prototype.doPhysics = function(dt) {
      var id, player, ref, results;
      ref = this.players;
      results = [];
      for (id in ref) {
        player = ref[id];
        results.push(this.players[id] = this.movePlayer(player, dt));
      }
      return results;
    };

    LOOP_TIME_INTERVAL = 10;

    Game.prototype.loop = function() {
      var diff, startTime;
      startTime = new Date().getTime();
      this.doPhysics(LOOP_TIME_INTERVAL / 1000.0);
      this.broadcastState();
      diff = LOOP_TIME_INTERVAL - ((new Date().getTime()) - startTime);
      if (diff < 0) {
        console.log("WARNING: Game loop computation too slow!");
        diff = 0;
      }
      return setTimeout(this.loop, diff);
    };

    return Game;

  })();

  module.exports = Game;

}).call(this);

//# sourceMappingURL=index.js.map
