// Generated by CoffeeScript 1.8.0
(function() {
  var Game;

  Game = (function() {
    function Game() {
      this.worldWidth = 4000;
      this.worldHeight = 4000;
      this.players = {};
      this.nextPlayerId = 0;
      this.enemies = {};
      this.bullets = {};
      this.io = null;
    }

    Game.prototype.start = function(io) {
      return io.on('connection', (function(_this) {
        return function(socket) {
          return _this.initializeConnection(socket);
        };
      })(this));
    };

    Game.prototype.initializeConnection = function(socket) {
      var newPlayerId;
      socket.on("move", this.handleMove);
      newPlayerId = this.nextPlayerId++;
      return socket.emit({
        playerId: newPlayerId
      });
    };

    Game.prototype.handleMove = function(from, message) {
      var mouseX, mouseY, playerId;
      mouseX = message.mouseX, mouseY = message.mouseY;
      return playerId = from;
    };

    return Game;

  })();

  module.exports = Game;

}).call(this);

//# sourceMappingURL=index.js.map
